document.querySelector(".three").addEventListener("click",()=>{
    document.querySelector(".projects-section").scrollIntoView({behavior:"smooth"})
});
document.querySelector("#home").addEventListener("click",()=>{
    document.querySelector(".intro").scrollIntoView({behavior:"smooth"})
});
document.querySelector("#about").addEventListener("click",()=>{
    document.querySelector(".about-section").scrollIntoView({behavior:"smooth"})
});
document.querySelector("#projects").addEventListener("click",()=>{
    document.querySelector(".projects-section").scrollIntoView({behavior:"smooth"})
});
document.querySelector("#skills").addEventListener("click",()=>{
    document.querySelector(".skills-section").scrollIntoView({behavior:"smooth"})
});
document.querySelector("#contact").addEventListener("click",()=>{
    document.querySelector(".contact-section").scrollIntoView({behavior:"smooth"})
});

document.querySelector(".toggle").addEventListener("click",()=>{
if(document.querySelector("#theme").getAttribute("href")=="dark-mode.css"){
    document.querySelector("#theme").setAttribute("href","light-mode.css")
    document.querySelector(".circle").style.transform="translateX(-1.5px)"
    document.querySelector(".circle").style.backgroundColor="var(--seccolor)"
}
else{
    document.querySelector("#theme").setAttribute("href","dark-mode.css")
    document.querySelector(".circle").style.transform="translateX(20px)"
    document.querySelector(".circle").style.backgroundColor="rgb(0,123,255)"
    document.querySelector(".circle").style.transition="all 0.2s ease-in-out"
}}
)